### ISSUE TITLE
Single scroll ticks don't work

### ISSUE THREAD

**Issue by Hedgehogs4Me** [emreyolcu/discrete-scroll#1]
Hi,

I ran the .app binary that you posted to AskDifferent, and it ran fine, making the scroll linear and discrete, except for the first few scroll ticks. In particular, I would like my scroll wheel to register when I scroll one tick and then stop, as this is necessary for several programs, especially games.

I'm not getting any errors when running from Terminal. I suggest maybe that this is caused by that a single lone scroll tick doesn't register as any distance using the unmodified scrolling behavior.

**Comment by emreyolcu** [comment]
Hello,

Are you running OS X version 10.12 or newer? Several other people encountered the problem you described and it is caused by `kCGScrollWheelEventDeltaAxis1` being `0` for the first few scroll ticks. Changing that field to `kCGScrollWheelEventPointDeltaAxis1` should solve this problem. 

I am running 10.9.5 and line delta is never zero, although it really should be for the first few ticks since the scrolling does not amount to a line. I guess Apple fixed it some release after 10.9.5.

Here is the binary that should work:
https://github.com/emreyolcu/discrete-scroll/releases/download/v0.1.1/DiscreteScroll.zip

**Comment by Hedgehogs4Me** [comment]
Yes, I'm currently running 10.12.1 and this works gloriously. Thank you!

**Comment by emreyolcu** [comment]
I'm glad that it works!
