### ISSUE TITLE
The app does nothing

### ISSUE THREAD

**Issue by Johnrobmiller** [emreyolcu/discrete-scroll#29]
Downloaded it, tried to run it but double clicking on the app does nothing.  There are no errors, no warnings, just silence.

**Comment by rienst** [comment]
I recently started using an M1 MacBook and on it, the app does not work. It still works with my other Intel MacBook. Could that be the issue?

**Comment by emreyolcu** [comment]
Could you try the binaries [in this link](https://github.com/iwa/discrete-scroll-arm/releases/tag/v0.1.1u)?

**Comment by Johnrobmiller** [comment]
For me, the problem was that there was another app that was taking over the mouse, but I did not know about it.

**Comment by emreyolcu** [comment]
In that case, is it okay to close the issue?

**Comment by Johnrobmiller** [comment]
I know I'm not a dev on this project, but I would say it would be better ux to display an error message on the app when the mouse is getting hogged by another program. Right now, there is only silence, which is not good ux.

**Comment by bandtank** [comment]
@Johnrobmiller It isn't always possible to know. You also could have made your point more politely. @emreyolcu provided a free solution to an incredibly annoying problem. "There is an opportunity to improve the UX by warning the user about other programs that may be influencing the behavior of the mouse." is a lot more productive than "the ux isn't good."

**Comment by emreyolcu** [comment]
> I know I'm not a dev on this project, but I would say it would be better ux to display an error message on the app when the mouse is getting hogged by another program. Right now, there is only silence, which is not good ux.

In my view the default scrolling behavior is a bug and should have already been fixed by Apple, so I like that this program is completely out of sight. At the time I wrote this little utility there were no alternatives to solve this problem other than [USB Overdrive](https://www.usboverdrive.com/), and the documentation for the exact way to solve it took some figuring out, so I thought it was worth sharing with people.

There are now several nicer, feature-filled alternatives with much better UX you might prefer:
- https://github.com/linearmouse/linearmouse (I think this one is especially clean.)
- https://github.com/noah-nuebling/mac-mouse-fix
- https://github.com/gavinlynch/scroll-sanity
