### ISSUE TITLE
App is no longer working on launch

### ISSUE THREAD

**Issue by abby-loopy** [emreyolcu/discrete-scroll#35]
I tried restarting my computer and deleting and reinstalling the app, but it isn't functioning for me anymore. Still experiencing the scroll acceleration :/ Not sure if anyone else is having this issue.

**Comment by vonneudeck** [comment]
This issue started with the new MacOS version `13.2.1 (22D68)` and if one starts it manually this error message appears (translation in alt attribute).
<img width="279" alt="Error Message that DiscreteScrollApp can't be loaded because Apple can't search it for malware" src="https://user-images.githubusercontent.com/3678775/220437706-4a4924ba-f131-4f5e-a2cf-39a49be8be87.png">

**Comment by Anuken** [comment]
A fix for anyone experiencing this: Run `xattr -d com.apple.quarantine DiscreteScroll.app` in the terminal.

Works on MacOS 14.2 for me.

**Comment by emreyolcu** [comment]
Please see issues #25, #40, and the instructions I have recently added to the README.
